language: php

php:
  - 7.3
  - 7.2
  - 7.1
  - 7.0

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_script:
  - composer update --prefer-dist

script:
  - ./vendor/bin/phpcs -n .
  - ./vendor/bin/phpunit

after_script:
  - php vendor/bin/php-coveralls -v
